default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: username
  password: password

development:
  <<: *default
  database: app-api_development
  adapter: postgresql
  username: username
  password: password

test:
  <<: *default
  database: app-api_test
  adapter: postgresql
  username: username
  password: password

production:
  <<: *default
  adapter: postgresql
  database: app-api_production
  username: username
  password: <%= ENV['APP-API_DATABASE_PASSWORD'] %>
